security.oauth2.client:
    clientId: acme_ext
    clientSecret: acmesecret_ext
    authorized-grant-types: refresh_token,password
    scope: openid
    
server:
    port: 9999
    contextPath: /uaa
    
security:
    user.password: password
    
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
